export const localeOrder = ["pt-BR", "en", "es"];

export const locales = {
  "pt-BR": {
    htmlLang: "pt-BR",
    ogLocale: "pt_BR",
    short: "PT",
    nativeName: "Português",
    home: "/",
    routes: {
      about: "/sobre/",
      contact: "/contato/",
      privacy: "/privacidade/",
      projects: "/projetos/",
    },
    common: {
      brandTagline: "Produto · software · criação",
      navLabel: "Navegação principal",
      products: "Projetos",
      about: "Sobre",
      contact: "Contato",
      talk: "Falar comigo",
      theme: "Alterar tema",
      language: "Idioma",
      languageMenu: "Escolher idioma",
      skip: "Ir para o conteúdo",
      footerLabel: "Rodapé",
      privacy: "Privacidade",
      cookies: "Cookies",
      email: "E-mail",
      previous: "Anterior",
      next: "Próximo",
      viewProject: "Conhecer projeto",
      backToProjects: "Voltar aos projetos",
      nextProject: "Próximo projeto",
      galleryPrevious: "Imagem anterior",
      galleryNext: "Próxima imagem",
      galleryLabel: "Galeria do projeto",
      detailsLabel: "Detalhes do projeto",
      external: "abre em nova aba",
      copyright: "Guilherme Rocha.",
    },
    homePage: {
      title: "Gui Rocha — software, jogos e ferramentas locais",
      description: "Portfólio de Gui Rocha: ClubAL, Maeve Roscaern, Codex Checkpoint, NEXUS e projetos web apresentados com estado e evidências reais.",
      eyebrow: "Gui Rocha · Product Owner e socioeducador",
      heading: "Eu crio software para organizar o trabalho — e jogos para explorar outros mundos.",
      lead: "Desenvolvo o ClubAL, Maeve Roscaern e ferramentas locais para acompanhar projetos assistidos por agentes.",
      primaryAction: "Ver projetos",
      secondaryAction: "Falar comigo",
      catalogTitle: "Projetos",
      catalogHint: "Escolha um projeto ou use os botões Anterior e Próximo.",
      portraitAlt: "Retrato de Guilherme Rocha",
      portraitCaption: "Alfenas, Brasil",
      noscript: "Escolha um projeto:",
    },
    aboutPage: {
      title: "Sobre Gui Rocha",
      description: "Como Gui Rocha conduz produtos digitais, software local e projetos criativos com apoio de agentes de código.",
      eyebrow: "Sobre",
      heading: "Trabalho solo. As decisões de produto continuam humanas.",
      lead: "Eu defino o problema, o recorte, a experiência e o que precisa ser comprovado. Agentes de código me ajudam a implementar e testar; conceito, protótipo e produto são apresentados pelo nome certo.",
      primaryAction: "Ver projetos",
      secondaryAction: "Abrir GitHub",
      landscapeAlt: "Guilherme Rocha observando uma paisagem de cânions e água",
      landscapeKicker: "Mapa dos trabalhos",
      landscapeTitle: "Produtos diferentes pedem ritmos diferentes.",
      landscapeBody: "O ClubAL organiza rotinas; Maeve constrói um mundo; Checkpoint e NEXUS organizam o próprio processo de desenvolvimento.",
      landscapeCaption: "Arquivo pessoal · Serra da Canastra",
      musicAlt: "Guilherme Rocha tocando violão",
      musicKicker: "Fora da tela",
      musicTitle: "Música, escrita e trabalho socioeducativo também entram no processo.",
      musicBody: "Essas experiências influenciam como observo ritmo, linguagem e pessoas — e ajudam a não tratar produto como uma coleção de telas.",
      methodTitle: "Como eu trabalho",
      method: [
        ["01", "Produto", "Começo pelo problema, pelo público e pela decisão que o produto precisa facilitar."],
        ["02", "Execução", "Uso automação e agentes para ampliar uma produção solo sem terceirizar a direção."],
        ["03", "Evidência", "Testes automáticos e validação humana são separados; limites permanecem visíveis."],
      ],
    },
    contactPage: {
      title: "Contato — Gui Rocha",
      description: "Fale diretamente com Gui Rocha por WhatsApp comercial, e-mail ou GitHub.",
      eyebrow: "Contato direto",
      heading: "Escolha o canal. A conversa vai direto para mim.",
      lead: "Não há formulário, cadastro ou fila automática. Use WhatsApp para uma conversa comercial, e-mail para contexto mais longo ou GitHub para conhecer o trabalho público.",
      whatsapp: "WhatsApp comercial",
      whatsappDetail: "Mensagem para Guilherme Rocha",
      githubDetail: "@gmdr2022",
    },
    privacyPage: {
      title: "Privacidade — Gui Rocha",
      description: "Política de privacidade, cookies e armazenamento local do portfólio de Gui Rocha.",
      eyebrow: "Privacidade",
      heading: "Coleta mínima e controles locais.",
      lead: "Este portfólio não usa publicidade, pixel de marketing, conta de usuário, formulário ou analytics. Preferências visuais ficam no seu navegador.",
      updated: "Última atualização: 26 de julho de 2026.",
      indexTitle: "Nesta página",
      sections: [
        {
          id: "dados",
          title: "Dados e hospedagem",
          body: "O código não cria perfil nem recebe dados por formulário. A Cloudflare hospeda e entrega os arquivos e pode processar metadados técnicos de requisição segundo suas próprias políticas e necessidades operacionais. Este portfólio não adiciona banco de dados nem acesso público a logs.",
        },
        {
          id: "cookies",
          title: "Cookies e armazenamento local",
          body: "O cookie gui_consent registra por até 180 dias se você escolheu somente o essencial ou permitiu preferências. Tema e ajustes de acessibilidade ficam no localStorage apenas com sua permissão; sem ela, duram somente na sessão. O service worker pode guardar cópias dos arquivos públicos para tornar o carregamento mais resiliente.",
        },
        {
          id: "externos",
          title: "Links externos",
          body: "WhatsApp, GitHub, e-mail e sites de projetos só recebem uma navegação quando você decide abrir o link. A partir daí, o tratamento de dados pertence ao serviço escolhido.",
        },
        {
          id: "controle",
          title: "Seus controles",
          body: "O botão Cookies permite trocar sua escolha. O ícone de acessibilidade altera tamanho do texto, contraste, movimento e fonte. Você também pode apagar cookies, armazenamento e cache nas configurações do navegador.",
        },
        {
          id: "contato-privacidade",
          title: "Contato",
          body: "Dúvidas sobre esta página podem ser enviadas para suporte.clubal@gmail.com.",
        },
      ],
    },
    notFoundPage: {
      title: "Página não encontrada — Gui Rocha",
      eyebrow: "Erro 404",
      heading: "Este endereço não existe.",
      lead: "O catálogo continua disponível. Volte aos projetos ou fale comigo.",
      primaryAction: "Ver projetos",
      secondaryAction: "Contato",
    },
  },
  en: {
    htmlLang: "en",
    ogLocale: "en_US",
    short: "EN",
    nativeName: "English",
    home: "/en/",
    routes: {
      about: "/en/about/",
      contact: "/en/contact/",
      privacy: "/en/privacy/",
      projects: "/en/projects/",
    },
    common: {
      brandTagline: "Product · software · creation",
      navLabel: "Main navigation",
      products: "Projects",
      about: "About",
      contact: "Contact",
      talk: "Contact me",
      theme: "Change theme",
      language: "Language",
      languageMenu: "Choose language",
      skip: "Skip to content",
      footerLabel: "Footer",
      privacy: "Privacy",
      cookies: "Cookies",
      email: "Email",
      previous: "Previous",
      next: "Next",
      viewProject: "View project",
      backToProjects: "Back to projects",
      nextProject: "Next project",
      galleryPrevious: "Previous image",
      galleryNext: "Next image",
      galleryLabel: "Project gallery",
      detailsLabel: "Project details",
      external: "opens in a new tab",
      copyright: "Guilherme Rocha.",
    },
    homePage: {
      title: "Gui Rocha — software, games and local tools",
      description: "Gui Rocha’s portfolio: ClubAL, Maeve Roscaern, Codex Checkpoint, NEXUS and web projects presented with real status and evidence.",
      eyebrow: "Gui Rocha · Product Owner and social educator",
      heading: "I build software to organize work — and games to explore other worlds.",
      lead: "I develop ClubAL, Maeve Roscaern and local tools for managing agent-assisted projects.",
      primaryAction: "View projects",
      secondaryAction: "Contact me",
      catalogTitle: "Projects",
      catalogHint: "Choose a project or use the Previous and Next buttons.",
      portraitAlt: "Portrait of Guilherme Rocha",
      portraitCaption: "Alfenas, Brazil",
      noscript: "Choose a project:",
    },
    aboutPage: {
      title: "About Gui Rocha",
      description: "How Gui Rocha leads digital products, local software and creative projects with coding agents.",
      eyebrow: "About",
      heading: "I work independently. Product decisions stay human.",
      lead: "I define the problem, scope, experience and what needs to be proven. Coding agents help me implement and test; concepts, prototypes and products are labeled for what they are.",
      primaryAction: "View projects",
      secondaryAction: "Open GitHub",
      landscapeAlt: "Guilherme Rocha looking over a canyon and water landscape",
      landscapeKicker: "Map of the work",
      landscapeTitle: "Different products need different rhythms.",
      landscapeBody: "ClubAL organizes routines; Maeve builds a world; Checkpoint and NEXUS organize the development process itself.",
      landscapeCaption: "Personal archive · Serra da Canastra",
      musicAlt: "Guilherme Rocha playing guitar",
      musicKicker: "Beyond the screen",
      musicTitle: "Music, writing and social education are also part of the process.",
      musicBody: "They shape how I think about rhythm, language and people — and help me avoid treating a product as a collection of screens.",
      methodTitle: "How I work",
      method: [
        ["01", "Product", "I start with the problem, the audience and the decision the product should make easier."],
        ["02", "Execution", "I use automation and agents to extend solo production without outsourcing direction."],
        ["03", "Evidence", "Automated checks and human validation stay separate; limits remain visible."],
      ],
    },
    contactPage: {
      title: "Contact — Gui Rocha",
      description: "Contact Gui Rocha directly through business WhatsApp, email or GitHub.",
      eyebrow: "Direct contact",
      heading: "Choose a channel. The conversation comes directly to me.",
      lead: "There is no form, account or automated queue. Use WhatsApp for a business conversation, email for longer context or GitHub to review my public work.",
      whatsapp: "Business WhatsApp",
      whatsappDetail: "Message Guilherme Rocha",
      githubDetail: "@gmdr2022",
    },
    privacyPage: {
      title: "Privacy — Gui Rocha",
      description: "Privacy, cookie and local storage policy for Gui Rocha’s portfolio.",
      eyebrow: "Privacy",
      heading: "Minimal collection and local controls.",
      lead: "This portfolio does not use advertising, marketing pixels, user accounts, forms or analytics. Visual preferences stay in your browser.",
      updated: "Last updated: July 26, 2026.",
      indexTitle: "On this page",
      sections: [
        {
          id: "data",
          title: "Data and hosting",
          body: "The code does not create profiles or receive form data. Cloudflare hosts and serves the files and may process technical request metadata under its own policies and operational needs. This portfolio does not add a database or public log access.",
        },
        {
          id: "cookies",
          title: "Cookies and local storage",
          body: "The gui_consent cookie records for up to 180 days whether you chose essential storage only or allowed preferences. Theme and accessibility settings remain in localStorage only with permission; otherwise they last for the session. The service worker may cache public files for more resilient loading.",
        },
        {
          id: "external",
          title: "External links",
          body: "WhatsApp, GitHub, email and project websites only receive a navigation when you choose to open the link. From that point, the selected service handles data under its own terms.",
        },
        {
          id: "controls",
          title: "Your controls",
          body: "The Cookies button lets you change your choice. The accessibility button adjusts text size, contrast, motion and font. You can also clear cookies, storage and cache in your browser settings.",
        },
        {
          id: "privacy-contact",
          title: "Contact",
          body: "Questions about this page can be sent to suporte.clubal@gmail.com.",
        },
      ],
    },
    notFoundPage: {
      title: "Page not found — Gui Rocha",
      eyebrow: "Error 404",
      heading: "This address does not exist.",
      lead: "The project catalog is still available. Return to the projects or contact me.",
      primaryAction: "View projects",
      secondaryAction: "Contact",
    },
  },
  es: {
    htmlLang: "es",
    ogLocale: "es_ES",
    short: "ES",
    nativeName: "Español",
    home: "/es/",
    routes: {
      about: "/es/sobre/",
      contact: "/es/contacto/",
      privacy: "/es/privacidad/",
      projects: "/es/proyectos/",
    },
    common: {
      brandTagline: "Producto · software · creación",
      navLabel: "Navegación principal",
      products: "Proyectos",
      about: "Sobre mí",
      contact: "Contacto",
      talk: "Hablar conmigo",
      theme: "Cambiar tema",
      language: "Idioma",
      languageMenu: "Elegir idioma",
      skip: "Ir al contenido",
      footerLabel: "Pie de página",
      privacy: "Privacidad",
      cookies: "Cookies",
      email: "Correo",
      previous: "Anterior",
      next: "Siguiente",
      viewProject: "Ver proyecto",
      backToProjects: "Volver a proyectos",
      nextProject: "Siguiente proyecto",
      galleryPrevious: "Imagen anterior",
      galleryNext: "Siguiente imagen",
      galleryLabel: "Galería del proyecto",
      detailsLabel: "Detalles del proyecto",
      external: "se abre en una pestaña nueva",
      copyright: "Guilherme Rocha.",
    },
    homePage: {
      title: "Gui Rocha — software, juegos y herramientas locales",
      description: "Portafolio de Gui Rocha: ClubAL, Maeve Roscaern, Codex Checkpoint, NEXUS y proyectos web presentados con estado y evidencias reales.",
      eyebrow: "Gui Rocha · Product Owner y educador social",
      heading: "Creo software para organizar el trabajo y juegos para explorar otros mundos.",
      lead: "Desarrollo ClubAL, Maeve Roscaern y herramientas locales para gestionar proyectos asistidos por agentes.",
      primaryAction: "Ver proyectos",
      secondaryAction: "Hablar conmigo",
      catalogTitle: "Proyectos",
      catalogHint: "Elija un proyecto o use los botones Anterior y Siguiente.",
      portraitAlt: "Retrato de Guilherme Rocha",
      portraitCaption: "Alfenas, Brasil",
      noscript: "Elija un proyecto:",
    },
    aboutPage: {
      title: "Sobre Gui Rocha",
      description: "Cómo Gui Rocha dirige productos digitales, software local y proyectos creativos con agentes de código.",
      eyebrow: "Sobre mí",
      heading: "Trabajo de forma independiente. Las decisiones de producto siguen siendo humanas.",
      lead: "Defino el problema, el alcance, la experiencia y lo que debe demostrarse. Los agentes de código me ayudan a implementar y probar; cada concepto, prototipo y producto se presenta como lo que es.",
      primaryAction: "Ver proyectos",
      secondaryAction: "Abrir GitHub",
      landscapeAlt: "Guilherme Rocha observando un paisaje de cañones y agua",
      landscapeKicker: "Mapa de los trabajos",
      landscapeTitle: "Productos diferentes necesitan ritmos diferentes.",
      landscapeBody: "ClubAL organiza rutinas; Maeve construye un mundo; Checkpoint y NEXUS organizan el propio proceso de desarrollo.",
      landscapeCaption: "Archivo personal · Serra da Canastra",
      musicAlt: "Guilherme Rocha tocando la guitarra",
      musicKicker: "Fuera de la pantalla",
      musicTitle: "La música, la escritura y la educación social también forman parte del proceso.",
      musicBody: "Influyen en cómo observo el ritmo, el lenguaje y las personas, y evitan que trate un producto como una colección de pantallas.",
      methodTitle: "Cómo trabajo",
      method: [
        ["01", "Producto", "Empiezo por el problema, el público y la decisión que el producto debe facilitar."],
        ["02", "Ejecución", "Uso automatización y agentes para ampliar una producción individual sin delegar la dirección."],
        ["03", "Evidencia", "Las pruebas automáticas y la validación humana permanecen separadas; los límites siguen visibles."],
      ],
    },
    contactPage: {
      title: "Contacto — Gui Rocha",
      description: "Hable directamente con Gui Rocha por WhatsApp comercial, correo o GitHub.",
      eyebrow: "Contacto directo",
      heading: "Elija el canal. La conversación llega directamente a mí.",
      lead: "No hay formulario, registro ni cola automática. Use WhatsApp para una conversación comercial, correo para un contexto más amplio o GitHub para conocer mi trabajo público.",
      whatsapp: "WhatsApp comercial",
      whatsappDetail: "Mensaje para Guilherme Rocha",
      githubDetail: "@gmdr2022",
    },
    privacyPage: {
      title: "Privacidad — Gui Rocha",
      description: "Política de privacidad, cookies y almacenamiento local del portafolio de Gui Rocha.",
      eyebrow: "Privacidad",
      heading: "Recopilación mínima y controles locales.",
      lead: "Este portafolio no usa publicidad, píxeles de marketing, cuentas de usuario, formularios ni analítica. Las preferencias visuales permanecen en su navegador.",
      updated: "Última actualización: 26 de julio de 2026.",
      indexTitle: "En esta página",
      sections: [
        {
          id: "datos",
          title: "Datos y hospedaje",
          body: "El código no crea perfiles ni recibe datos por formulario. Cloudflare hospeda y entrega los archivos y puede procesar metadatos técnicos de las solicitudes según sus políticas y necesidades operativas. Este portafolio no añade una base de datos ni acceso público a registros.",
        },
        {
          id: "cookies",
          title: "Cookies y almacenamiento local",
          body: "La cookie gui_consent registra durante hasta 180 días si eligió solo lo esencial o permitió preferencias. El tema y los ajustes de accesibilidad permanecen en localStorage solo con permiso; sin él, duran durante la sesión. El service worker puede guardar archivos públicos para una carga más resistente.",
        },
        {
          id: "externos",
          title: "Enlaces externos",
          body: "WhatsApp, GitHub, correo y los sitios de proyectos solo reciben una navegación cuando usted decide abrir el enlace. A partir de ese momento, el servicio elegido trata los datos según sus propios términos.",
        },
        {
          id: "controles",
          title: "Sus controles",
          body: "El botón Cookies permite cambiar su elección. El botón de accesibilidad ajusta tamaño del texto, contraste, movimiento y fuente. También puede borrar cookies, almacenamiento y caché en el navegador.",
        },
        {
          id: "contacto-privacidad",
          title: "Contacto",
          body: "Las preguntas sobre esta página pueden enviarse a suporte.clubal@gmail.com.",
        },
      ],
    },
    notFoundPage: {
      title: "Página no encontrada — Gui Rocha",
      eyebrow: "Error 404",
      heading: "Esta dirección no existe.",
      lead: "El catálogo de proyectos sigue disponible. Vuelva a los proyectos o hable conmigo.",
      primaryAction: "Ver proyectos",
      secondaryAction: "Contacto",
    },
  },
};
