export const localeOrder = ["pt-BR", "en", "es"];

export const siteConfig = {
  origin: "https://gui-rocha.pages.dev",
  personalEmail: "gmdr2014@gmail.com",
  clubalEmail: "suporte.clubal@gmail.com",
  githubUrl: "https://github.com/gmdr2022",
  whatsappUrl: "https://wa.me/message/ACPGLFOEHUC7F1",
};

export const locales = {
  "pt-BR": {
    htmlLang: "pt-BR",
    ogLocale: "pt_BR",
    short: "PT",
    nativeName: "Português",
    home: "/",
    routes: {
      about: "/",
      contact: "/contato/",
      privacy: "/privacidade/",
      projects: "/projetos/",
      sites: "/sites/",
    },
    common: {
      brandTagline: "Projetos digitais com aplicação prática",
      navLabel: "Navegação principal",
      products: "Projetos",
      about: "Sobre",
      contact: "Contato",
      theme: "Alterar tema",
      themeInitial: "Tema: sistema",
      language: "Idioma",
      languageMenu: "Escolher idioma",
      skip: "Ir para o conteúdo",
      footerLabel: "Rodapé",
      privacy: "Privacidade",
      cookies: "Cookies",
      email: "E-mail",
      previous: "Anterior",
      next: "Próximo",
      carousel: "carrossel",
      viewProject: "Conhecer projeto",
      backToProjects: "Voltar aos projetos",
      nextProject: "Próximo projeto",
      galleryPrevious: "Imagem anterior",
      galleryNext: "Próxima imagem",
      galleryLabel: "Galeria do projeto",
      detailsLabel: "Detalhes do projeto",
      clubalSupport: "Suporte do ClubAL",
      caseLabels: {
        context: "Contexto",
        role: "Papel",
        problem: "Problema",
        contribution: "Contribuição e decisões",
        evidence: "Evidência e resultado",
        status: "Estado e limites",
      },
      external: "abre em nova aba",
      copyright: "Guilherme Rocha.",
    },
    aboutPage: {
      title: "Gui Rocha — direção de produto e soluções digitais",
      description: "Portfólio de Guilherme Rocha com direção de produto, construção digital e projetos aplicados a problemas reais.",
      eyebrow: "PORTFÓLIO",
      heading: "Começo pelo problema e acompanho cada etapa até a entrega.",
      lead: "Transformo necessidades reais em produtos digitais claros, úteis e possíveis de manter. Atuo da direção de produto à construção, com atenção ao contexto, às pessoas e às evidências de que a solução funciona.",
      role: "Product Owner e criador de produtos digitais",
      primaryAction: "Explorar projetos",
      tertiaryAction: "Ver trabalho no GitHub",
      portraitAlt: "Guilherme Rocha em uma área de embarque ao entardecer",
      portraitCaption: "Minas Gerais, Brasil",
      landscapeAlt: "Retrato de Guilherme Rocha com camisa clara em um ambiente interno",
      landscapeKicker: "Mapa do meu trabalho",
      landscapeTitle: "Problemas diferentes, o mesmo compromisso com uma entrega que funcione.",
      landscapeBody: "Produtos institucionais, ferramentas locais, sites e experiências autorais começam pelo contexto de uso. O escopo muda; o cuidado com clareza, continuidade e resultado permanece.",
      landscapeCaption: "Retrato autoral · arquivo pessoal",
      catalogKicker: "Explorar por contexto",
      catalogHint: "Escolha um contexto para conhecer os projetos relacionados.",
      catalogSingle: "projeto",
      catalogMultiple: "projetos",
      catalogs: [
        ["institutional", "Operações institucionais", ["clubal"]],
        ["websites", "Presença digital", ["sites"]],
        ["local-tools", "Ferramentas de trabalho", ["nexus", "codex-checkpoint"]],
        ["engineering", "Métodos de desenvolvimento", ["local-first-checklist", "c7-engineering-system"]],
        ["original", "Projetos autorais", ["maeve"]],
      ],
      methodEyebrow: "Como trabalho",
      methodTitle: "Do problema à evidência, sem esconder o que ainda está em evolução.",
      method: [
        ["01", "Problema", "Compreendo contexto, público e a decisão que precisa ser tomada."],
        ["02", "Direção", "Defino recorte, prioridade, critérios e trade-offs antes de ampliar o escopo."],
        ["03", "Construção", "Avanço em etapas controláveis, preservando experiência e manutenção."],
        ["04", "Evidência", "Testo, registro o estado e declaro com clareza os limites da entrega."],
      ],
    },
    projectsPage: {
      title: "Projetos digitais — Gui Rocha",
      description: "Projetos digitais de Gui Rocha apresentados com contexto, estado atual, evidências e limites claros.",
      eyebrow: "Projetos",
      heading: "Produtos digitais construídos para problemas reais.",
      catalogHint: "Escolha um projeto ou use os controles Anterior e Próximo.",
      noscript: "Todos os projetos:",
    },
    contactPage: {
      title: "Contato — Gui Rocha",
      description: "Converse com Guilherme Rocha sobre produtos, sistemas, sites e projetos digitais.",
      eyebrow: "Contato",
      heading: "Vamos conversar.",
      lead: "O contato está aberto para oportunidades profissionais, parcerias e projetos. Envie o contexto e o que precisa ser avaliado para definirmos o próximo passo.",
      guidance: "Para facilitar, inclua objetivo, cenário atual, prazo e restrições relevantes.",
      talkHeading: "Contato pessoal e profissional",
      publicWorkHeading: "Trabalho público",
      personalEmailLabel: "E-mail principal",
      clubalHeading: "Contato do ClubAL",
      clubalBody: "Para suporte, demonstração, parceria ou qualquer assunto específico do ClubAL, use o canal dedicado do produto.",
      clubalAction: "E-mail do ClubAL",
      clubalSubject: "Contato sobre ClubAL",
      contextLead: "Assunto selecionado: {project}. Conte o que você precisa e o contexto do projeto.",
      contextSubject: "Contato sobre {project}",
      whatsapp: "WhatsApp",
      whatsappDetail: "Iniciar conversa",
      githubDetail: "@gmdr2022",
    },
    privacyPage: {
      title: "Privacidade — Gui Rocha",
      description: "Política de privacidade, cookies e armazenamento local do portfólio de Gui Rocha.",
      eyebrow: "Privacidade",
      heading: "Coleta mínima e controles locais.",
      lead: "Este portfólio não usa publicidade, pixel de marketing, conta de usuário, formulário ou analytics. Preferências visuais ficam no seu navegador.",
      updated: "Última atualização: 17 de agosto de 2026.",
      indexTitle: "Nesta página",
      sections: [
        {
          id: "dados",
          title: "Dados e hospedagem",
          body: "O código não cria perfil nem recebe dados por formulário. A Cloudflare hospeda e entrega os arquivos e pode processar metadados técnicos de requisição segundo suas próprias políticas e necessidades operacionais. Este portfólio não adiciona banco de dados nem acesso público a logs.",
        },
        {
          id: "cookies",
          title: "Cookies e armazenamento local",
          body: "O cookie gui_consent registra por até 180 dias se você escolheu somente o essencial ou permitiu preferências. Tema e ajustes de acessibilidade ficam no localStorage apenas com sua permissão; sem ela, duram somente na sessão. O portal não mantém cache próprio por service worker; o código atual remove registros e caches legados deste domínio.",
        },
        {
          id: "externos",
          title: "Links externos",
          body: "WhatsApp, GitHub, e-mail e sites de projetos só recebem uma navegação quando você decide abrir o link. A partir daí, o tratamento de dados pertence ao serviço escolhido.",
        },
        {
          id: "controle",
          title: "Seus controles",
          body: "O botão Cookies permite trocar sua escolha. O ícone de acessibilidade altera tamanho do texto, contraste, movimento e fonte. Você também pode apagar cookies, armazenamento e cache nas configurações do navegador.",
        },
        {
          id: "contato-privacidade",
          title: "Contato",
          body: `Dúvidas sobre esta página podem ser enviadas para ${siteConfig.personalEmail}.`,
        },
      ],
    },
    notFoundPage: {
      title: "Página não encontrada — Gui Rocha",
      eyebrow: "Erro 404",
      heading: "Este endereço não existe.",
      lead: "O catálogo continua disponível. Volte aos projetos ou fale comigo.",
      primaryAction: "Explorar projetos",
      secondaryAction: "Contato",
    },
  },
  en: {
    htmlLang: "en",
    ogLocale: "en_US",
    short: "EN",
    nativeName: "English",
    home: "/en/",
    routes: {
      about: "/en/",
      contact: "/en/contact/",
      privacy: "/en/privacy/",
      projects: "/en/projects/",
      sites: "/en/sites/",
    },
    common: {
      brandTagline: "Digital projects with practical applications",
      navLabel: "Main navigation",
      products: "Projects",
      about: "About",
      contact: "Contact",
      theme: "Change theme",
      themeInitial: "Theme: system",
      language: "Language",
      languageMenu: "Choose language",
      skip: "Skip to content",
      footerLabel: "Footer",
      privacy: "Privacy",
      cookies: "Cookies",
      email: "Email",
      previous: "Previous",
      next: "Next",
      carousel: "carousel",
      viewProject: "View project",
      backToProjects: "Back to projects",
      nextProject: "Next project",
      galleryPrevious: "Previous image",
      galleryNext: "Next image",
      galleryLabel: "Project gallery",
      detailsLabel: "Project details",
      clubalSupport: "ClubAL support",
      caseLabels: {
        context: "Context",
        role: "Role",
        problem: "Problem",
        contribution: "Contribution and decisions",
        evidence: "Evidence and outcome",
        status: "Status and limits",
      },
      external: "opens in a new tab",
      copyright: "Guilherme Rocha.",
    },
    aboutPage: {
      title: "Gui Rocha — product direction and digital solutions",
      description: "Guilherme Rocha’s portfolio of product direction, digital creation and projects applied to real problems.",
      eyebrow: "PORTFOLIO",
      heading: "I start with the problem and follow every stage through delivery.",
      lead: "I turn real needs into clear, useful digital products that can be maintained. My work spans product direction and hands-on creation, with attention to context, people and evidence that the solution works.",
      role: "Product Owner and digital product creator",
      primaryAction: "Explore projects",
      tertiaryAction: "View work on GitHub",
      portraitAlt: "Guilherme Rocha in a boarding area at sunset",
      portraitCaption: "Minas Gerais, Brazil",
      landscapeAlt: "Portrait of Guilherme Rocha wearing a light shirt in an indoor setting",
      landscapeKicker: "Map of my work",
      landscapeTitle: "Different problems, the same commitment to a delivery that works.",
      landscapeBody: "Institutional products, local tools, websites and original experiences begin with their context of use. The scope changes; the care for clarity, continuity and outcomes remains.",
      landscapeCaption: "Author portrait · personal archive",
      catalogKicker: "Explore by context",
      catalogHint: "Choose a context to discover the related projects.",
      catalogSingle: "project",
      catalogMultiple: "projects",
      catalogs: [
        ["institutional", "Institutional operations", ["clubal"]],
        ["websites", "Digital presence", ["sites"]],
        ["local-tools", "Work tools", ["nexus", "codex-checkpoint"]],
        ["engineering", "Development methods", ["local-first-checklist", "c7-engineering-system"]],
        ["original", "Original projects", ["maeve"]],
      ],
      methodEyebrow: "How I work",
      methodTitle: "From problem to evidence, without hiding what is still evolving.",
      method: [
        ["01", "Problem", "I understand the context, audience and the decision that needs to be made."],
        ["02", "Direction", "I define the slice, priorities, criteria and trade-offs before expanding scope."],
        ["03", "Build", "I move forward in controlled stages, preserving experience and maintainability."],
        ["04", "Evidence", "I test, record the state and clearly declare the delivery's limits."],
      ],
    },
    projectsPage: {
      title: "Digital projects — Gui Rocha",
      description: "Gui Rocha’s digital projects, presented with context, current status, evidence and clear limits.",
      eyebrow: "Projects",
      heading: "Digital products built around real problems.",
      catalogHint: "Choose a project or use the Previous and Next controls.",
      noscript: "All projects:",
    },
    contactPage: {
      title: "Contact — Gui Rocha",
      description: "Talk with Guilherme Rocha about products, systems, websites and digital projects.",
      eyebrow: "Contact",
      heading: "Let’s talk.",
      lead: "I am open to professional opportunities, partnerships and projects. Share the context and what needs to be evaluated so we can define the next step.",
      guidance: "To make the conversation easier, include the objective, current situation, timeline and relevant constraints.",
      talkHeading: "Personal and professional contact",
      publicWorkHeading: "Public work",
      personalEmailLabel: "Primary email",
      clubalHeading: "ClubAL contact",
      clubalBody: "For support, a demonstration, a partnership or any ClubAL-specific topic, use the product’s dedicated channel.",
      clubalAction: "ClubAL email",
      clubalSubject: "Contact about ClubAL",
      contextLead: "Selected topic: {project}. Share what you need and the project context.",
      contextSubject: "Contact about {project}",
      whatsapp: "WhatsApp",
      whatsappDetail: "Start a conversation",
      githubDetail: "@gmdr2022",
    },
    privacyPage: {
      title: "Privacy — Gui Rocha",
      description: "Privacy, cookie and local storage policy for Gui Rocha’s portfolio.",
      eyebrow: "Privacy",
      heading: "Minimal collection and local controls.",
      lead: "This portfolio does not use advertising, marketing pixels, user accounts, forms or analytics. Visual preferences stay in your browser.",
      updated: "Last updated: August 17, 2026.",
      indexTitle: "On this page",
      sections: [
        {
          id: "data",
          title: "Data and hosting",
          body: "The code does not create profiles or receive form data. Cloudflare hosts and serves the files and may process technical request metadata under its own policies and operational needs. This portfolio does not add a database or public log access.",
        },
        {
          id: "cookies",
          title: "Cookies and local storage",
          body: "The gui_consent cookie records for up to 180 days whether you chose essential storage only or allowed preferences. Theme and accessibility settings remain in localStorage only with permission; otherwise they last for the session. The portal does not keep its own service worker cache; the current code removes legacy registrations and caches for this domain.",
        },
        {
          id: "external",
          title: "External links",
          body: "WhatsApp, GitHub, email and project websites only receive a navigation when you choose to open the link. From that point, the selected service handles data under its own terms.",
        },
        {
          id: "controls",
          title: "Your controls",
          body: "The Cookies button lets you change your choice. The accessibility button adjusts text size, contrast, motion and font. You can also clear cookies, storage and cache in your browser settings.",
        },
        {
          id: "privacy-contact",
          title: "Contact",
          body: `Questions about this page can be sent to ${siteConfig.personalEmail}.`,
        },
      ],
    },
    notFoundPage: {
      title: "Page not found — Gui Rocha",
      eyebrow: "Error 404",
      heading: "This address does not exist.",
      lead: "The project catalog is still available. Return to the projects or contact me.",
      primaryAction: "Explore projects",
      secondaryAction: "Contact",
    },
  },
  es: {
    htmlLang: "es",
    ogLocale: "es_ES",
    short: "ES",
    nativeName: "Español",
    home: "/es/",
    routes: {
      about: "/es/",
      contact: "/es/contacto/",
      privacy: "/es/privacidad/",
      projects: "/es/proyectos/",
      sites: "/es/sitios/",
    },
    common: {
      brandTagline: "Proyectos digitales con aplicación práctica",
      navLabel: "Navegación principal",
      products: "Proyectos",
      about: "Sobre mí",
      contact: "Contacto",
      theme: "Cambiar tema",
      themeInitial: "Tema: sistema",
      language: "Idioma",
      languageMenu: "Elegir idioma",
      skip: "Ir al contenido",
      footerLabel: "Pie de página",
      privacy: "Privacidad",
      cookies: "Cookies",
      email: "Correo",
      previous: "Anterior",
      next: "Siguiente",
      carousel: "carrusel",
      viewProject: "Ver proyecto",
      backToProjects: "Volver a proyectos",
      nextProject: "Siguiente proyecto",
      galleryPrevious: "Imagen anterior",
      galleryNext: "Siguiente imagen",
      galleryLabel: "Galería del proyecto",
      detailsLabel: "Detalles del proyecto",
      clubalSupport: "Soporte de ClubAL",
      caseLabels: {
        context: "Contexto",
        role: "Rol",
        problem: "Problema",
        contribution: "Contribución y decisiones",
        evidence: "Evidencia y resultado",
        status: "Estado y límites",
      },
      external: "se abre en una pestaña nueva",
      copyright: "Guilherme Rocha.",
    },
    aboutPage: {
      title: "Gui Rocha — dirección de producto y soluciones digitales",
      description: "Portafolio de Guilherme Rocha con dirección de producto, creación digital y proyectos aplicados a problemas reales.",
      eyebrow: "PORTAFOLIO",
      heading: "Comienzo por el problema y acompaño cada etapa hasta la entrega.",
      lead: "Transformo necesidades reales en productos digitales claros, útiles y fáciles de mantener. Trabajo desde la dirección de producto hasta la creación, con atención al contexto, a las personas y a la evidencia de que la solución funciona.",
      role: "Product Owner y creador de productos digitales",
      primaryAction: "Explorar proyectos",
      tertiaryAction: "Ver trabajo en GitHub",
      portraitAlt: "Guilherme Rocha en una zona de embarque al atardecer",
      portraitCaption: "Minas Gerais, Brasil",
      landscapeAlt: "Retrato de Guilherme Rocha con camisa clara en un ambiente interior",
      landscapeKicker: "Mapa de mi trabajo",
      landscapeTitle: "Problemas diferentes, el mismo compromiso con una entrega que funcione.",
      landscapeBody: "Los productos institucionales, las herramientas locales, los sitios y las experiencias originales comienzan por su contexto de uso. El alcance cambia; el cuidado por la claridad, la continuidad y el resultado permanece.",
      landscapeCaption: "Retrato de autor · archivo personal",
      catalogKicker: "Explorar por contexto",
      catalogHint: "Elija un contexto para conocer los proyectos relacionados.",
      catalogSingle: "proyecto",
      catalogMultiple: "proyectos",
      catalogs: [
        ["institutional", "Operaciones institucionales", ["clubal"]],
        ["websites", "Presencia digital", ["sites"]],
        ["local-tools", "Herramientas de trabajo", ["nexus", "codex-checkpoint"]],
        ["engineering", "Métodos de desarrollo", ["local-first-checklist", "c7-engineering-system"]],
        ["original", "Proyectos propios", ["maeve"]],
      ],
      methodEyebrow: "Cómo trabajo",
      methodTitle: "Del problema a la evidencia, sin ocultar lo que todavía está en evolución.",
      method: [
        ["01", "Problema", "Comprendo el contexto, el público y la decisión que debe tomarse."],
        ["02", "Dirección", "Defino el recorte, las prioridades, los criterios y los trade-offs antes de ampliar el alcance."],
        ["03", "Construcción", "Avanzo en etapas controlables, preservando la experiencia y el mantenimiento."],
        ["04", "Evidencia", "Pruebo, registro el estado y declaro con claridad los límites de la entrega."],
      ],
    },
    projectsPage: {
      title: "Proyectos digitales — Gui Rocha",
      description: "Proyectos digitales de Gui Rocha presentados con contexto, estado actual, evidencias y límites claros.",
      eyebrow: "Proyectos",
      heading: "Productos digitales construidos para problemas reales.",
      catalogHint: "Elija un proyecto o use los controles Anterior y Siguiente.",
      noscript: "Todos los proyectos:",
    },
    contactPage: {
      title: "Contacto — Gui Rocha",
      description: "Converse con Guilherme Rocha sobre productos, sistemas, sitios y proyectos digitales.",
      eyebrow: "Contacto",
      heading: "Hablemos.",
      lead: "Estoy abierto a oportunidades profesionales, colaboraciones y proyectos. Comparta el contexto y lo que necesita evaluar para que podamos definir el siguiente paso.",
      guidance: "Para facilitar la conversación, incluya el objetivo, la situación actual, el plazo y las restricciones relevantes.",
      talkHeading: "Contacto personal y profesional",
      publicWorkHeading: "Trabajo público",
      personalEmailLabel: "Correo principal",
      clubalHeading: "Contacto de ClubAL",
      clubalBody: "Para soporte, una demostración, una colaboración o cualquier tema específico de ClubAL, use el canal dedicado del producto.",
      clubalAction: "Correo de ClubAL",
      clubalSubject: "Contacto sobre ClubAL",
      contextLead: "Tema seleccionado: {project}. Cuénteme qué necesita y el contexto del proyecto.",
      contextSubject: "Contacto sobre {project}",
      whatsapp: "WhatsApp",
      whatsappDetail: "Iniciar una conversación",
      githubDetail: "@gmdr2022",
    },
    privacyPage: {
      title: "Privacidad — Gui Rocha",
      description: "Política de privacidad, cookies y almacenamiento local del portafolio de Gui Rocha.",
      eyebrow: "Privacidad",
      heading: "Recopilación mínima y controles locales.",
      lead: "Este portafolio no usa publicidad, píxeles de marketing, cuentas de usuario, formularios ni analítica. Las preferencias visuales permanecen en su navegador.",
      updated: "Última actualización: 17 de agosto de 2026.",
      indexTitle: "En esta página",
      sections: [
        {
          id: "datos",
          title: "Datos y hospedaje",
          body: "El código no crea perfiles ni recibe datos por formulario. Cloudflare hospeda y entrega los archivos y puede procesar metadatos técnicos de las solicitudes según sus políticas y necesidades operativas. Este portafolio no añade una base de datos ni acceso público a registros.",
        },
        {
          id: "cookies",
          title: "Cookies y almacenamiento local",
          body: "La cookie gui_consent registra durante hasta 180 días si eligió solo lo esencial o permitió preferencias. El tema y los ajustes de accesibilidad permanecen en localStorage solo con permiso; sin él, duran durante la sesión. El portal no mantiene una caché propia mediante service worker; el código actual elimina registros y cachés heredados de este dominio.",
        },
        {
          id: "externos",
          title: "Enlaces externos",
          body: "WhatsApp, GitHub, correo y los sitios de proyectos solo reciben una navegación cuando usted decide abrir el enlace. A partir de ese momento, el servicio elegido trata los datos según sus propios términos.",
        },
        {
          id: "controles",
          title: "Sus controles",
          body: "El botón Cookies permite cambiar su elección. El botón de accesibilidad ajusta tamaño del texto, contraste, movimiento y fuente. También puede borrar cookies, almacenamiento y caché en el navegador.",
        },
        {
          id: "contacto-privacidad",
          title: "Contacto",
          body: `Las preguntas sobre esta página pueden enviarse a ${siteConfig.personalEmail}.`,
        },
      ],
    },
    notFoundPage: {
      title: "Página no encontrada — Gui Rocha",
      eyebrow: "Error 404",
      heading: "Esta dirección no existe.",
      lead: "El catálogo de proyectos sigue disponible. Vuelva a los proyectos o hable conmigo.",
      primaryAction: "Explorar proyectos",
      secondaryAction: "Contacto",
    },
  },
};
