export const localeOrder = ["pt-BR", "en", "es"];

export const locales = {
  "pt-BR": {
    htmlLang: "pt-BR",
    ogLocale: "pt_BR",
    short: "PT",
    nativeName: "Português",
    home: "/",
    routes: {
      about: "/sobre/",
      contact: "/contato/",
      privacy: "/privacidade/",
      projects: "/projetos/",
      sites: "/sites/",
    },
    common: {
      brandTagline: "Produto · software · criação",
      navLabel: "Navegação principal",
      products: "Projetos",
      about: "Sobre",
      contact: "Contato",
      talk: "Falar comigo",
      theme: "Alterar tema",
      themeInitial: "Tema: sistema",
      language: "Idioma",
      languageMenu: "Escolher idioma",
      skip: "Ir para o conteúdo",
      footerLabel: "Rodapé",
      privacy: "Privacidade",
      cookies: "Cookies",
      email: "E-mail",
      previous: "Anterior",
      next: "Próximo",
      viewProject: "Conhecer projeto",
      backToProjects: "Voltar aos projetos",
      nextProject: "Próximo projeto",
      galleryPrevious: "Imagem anterior",
      galleryNext: "Próxima imagem",
      galleryLabel: "Galeria do projeto",
      detailsLabel: "Detalhes do projeto",
      external: "abre em nova aba",
      copyright: "Guilherme Rocha.",
    },
    homePage: {
      title: "Gui Rocha — produtos digitais, software e sites",
      description: "Portfólio de Guilherme Rocha: software local-first, ferramentas Windows, sites publicados e um RPG em produção, com escopo, estado e evidências claros.",
      eyebrow: "Gui Rocha · produto e criação digital",
      heading: "Produtos digitais para organizar operações, orientar decisões e construir experiências próprias.",
      lead: "Software local-first, ferramentas Windows, sites sob medida e um RPG em produção — cada entrega apresentada com escopo, estado e evidências claros.",
      primaryAction: "Explorar projetos",
      secondaryAction: "Discutir uma ideia",
      catalogTitle: "Projetos",
      catalogHint: "Escolha um projeto ou use os botões Anterior e Próximo.",
      portraitAlt: "Retrato de Guilherme Rocha",
      portraitCaption: "Alfenas, Brasil",
      noscript: "Escolha um projeto:",
    },
    aboutPage: {
      title: "Sobre mim — Gui Rocha",
      description: "Como Guilherme Rocha conduz produtos digitais, software local e projetos criativos da direção à entrega.",
      eyebrow: "Sobre mim",
      heading: "Direção de produto e execução técnica no mesmo processo.",
      lead: "Cada projeto começa pelo problema, recorta o essencial e avança em etapas verificáveis. Conceitos, protótipos e produtos aparecem pelo nome certo, com limites e estado atual visíveis.",
      primaryAction: "Explorar projetos",
      secondaryAction: "Abrir GitHub",
      landscapeAlt: "Guilherme Rocha observando uma paisagem de cânions e água",
      landscapeKicker: "Mapa do meu trabalho",
      landscapeTitle: "Escalas diferentes, o mesmo cuidado com o que precisa funcionar.",
      landscapeBody: "O ClubAL organiza rotinas institucionais; Maeve constrói um mundo; Checkpoint e NEXUS mantêm o desenvolvimento local orientado; os sites traduzem cada projeto para seu público.",
      landscapeCaption: "Arquivo pessoal · Serra da Canastra",
      catalogKicker: "Explorar por contexto",
      catalogHint: "Passe o cursor, use Tab ou clique para abrir uma categoria.",
      catalogSingle: "1 projeto",
      catalogMultiple: "projetos",
      catalogs: [
        ["institutional", "Softwares institucionais", ["clubal"]],
        ["games", "Jogos", ["maeve"]],
        ["websites", "Sites e experiências digitais", ["sites"]],
        ["windows", "Ferramentas Windows", ["nexus", "codex-checkpoint"]],
        ["resources", "Recursos", ["local-first-checklist", "c7-engineering-system"]],
      ],
      methodTitle: "Meu processo",
      method: [
        ["01", "Produto", "Problema, público e decisão orientam o primeiro recorte do produto."],
        ["02", "Construção", "Etapas pequenas mantêm escopo, experiência e manutenção sob controle."],
        ["03", "Evidência", "Testes sustentam o que pode ser afirmado; o que ainda evolui permanece explícito."],
      ],
    },
    contactPage: {
      title: "Contato — Gui Rocha",
      description: "Fale comigo diretamente pelo WhatsApp comercial, e-mail ou GitHub.",
      eyebrow: "Contato direto",
      heading: "Escolha o canal mais útil para o contexto.",
      lead: "A conversa chega diretamente a mim, sem formulário, cadastro ou fila automática. Use WhatsApp para um início comercial, e-mail para contexto mais longo ou GitHub para conhecer o trabalho público.",
      whatsapp: "WhatsApp comercial",
      whatsappDetail: "Enviar uma mensagem",
      githubDetail: "@gmdr2022",
    },
    privacyPage: {
      title: "Privacidade — Gui Rocha",
      description: "Política de privacidade, cookies e armazenamento local do portfólio de Gui Rocha.",
      eyebrow: "Privacidade",
      heading: "Coleta mínima e controles locais.",
      lead: "Este portfólio não usa publicidade, pixel de marketing, conta de usuário, formulário ou analytics. Preferências visuais ficam no seu navegador.",
      updated: "Última atualização: 26 de julho de 2026.",
      indexTitle: "Nesta página",
      sections: [
        {
          id: "dados",
          title: "Dados e hospedagem",
          body: "O código não cria perfil nem recebe dados por formulário. A Cloudflare hospeda e entrega os arquivos e pode processar metadados técnicos de requisição segundo suas próprias políticas e necessidades operacionais. Este portfólio não adiciona banco de dados nem acesso público a logs.",
        },
        {
          id: "cookies",
          title: "Cookies e armazenamento local",
          body: "O cookie gui_consent registra por até 180 dias se você escolheu somente o essencial ou permitiu preferências. Tema e ajustes de acessibilidade ficam no localStorage apenas com sua permissão; sem ela, duram somente na sessão. O portal não mantém cache próprio por service worker; o código atual remove registros e caches legados deste domínio.",
        },
        {
          id: "externos",
          title: "Links externos",
          body: "WhatsApp, GitHub, e-mail e sites de projetos só recebem uma navegação quando você decide abrir o link. A partir daí, o tratamento de dados pertence ao serviço escolhido.",
        },
        {
          id: "controle",
          title: "Seus controles",
          body: "O botão Cookies permite trocar sua escolha. O ícone de acessibilidade altera tamanho do texto, contraste, movimento e fonte. Você também pode apagar cookies, armazenamento e cache nas configurações do navegador.",
        },
        {
          id: "contato-privacidade",
          title: "Contato",
          body: "Dúvidas sobre esta página podem ser enviadas para suporte.clubal@gmail.com.",
        },
      ],
    },
    notFoundPage: {
      title: "Página não encontrada — Gui Rocha",
      eyebrow: "Erro 404",
      heading: "Este endereço não existe.",
      lead: "O catálogo continua disponível. Volte aos projetos ou fale comigo.",
      primaryAction: "Explorar projetos",
      secondaryAction: "Contato",
    },
  },
  en: {
    htmlLang: "en",
    ogLocale: "en_US",
    short: "EN",
    nativeName: "English",
    home: "/en/",
    routes: {
      about: "/en/about/",
      contact: "/en/contact/",
      privacy: "/en/privacy/",
      projects: "/en/projects/",
      sites: "/en/sites/",
    },
    common: {
      brandTagline: "Product · software · creation",
      navLabel: "Main navigation",
      products: "Projects",
      about: "About",
      contact: "Contact",
      talk: "Contact me",
      theme: "Change theme",
      themeInitial: "Theme: system",
      language: "Language",
      languageMenu: "Choose language",
      skip: "Skip to content",
      footerLabel: "Footer",
      privacy: "Privacy",
      cookies: "Cookies",
      email: "Email",
      previous: "Previous",
      next: "Next",
      viewProject: "View project",
      backToProjects: "Back to projects",
      nextProject: "Next project",
      galleryPrevious: "Previous image",
      galleryNext: "Next image",
      galleryLabel: "Project gallery",
      detailsLabel: "Project details",
      external: "opens in a new tab",
      copyright: "Guilherme Rocha.",
    },
    homePage: {
      title: "Gui Rocha — digital products, software and websites",
      description: "Guilherme Rocha’s portfolio: local-first software, Windows tools, published websites and an RPG in production, with clear scope, status and evidence.",
      eyebrow: "Gui Rocha · product and digital creation",
      heading: "Digital products that organize operations, guide decisions and build original experiences.",
      lead: "Local-first software, Windows tools, tailored websites and an RPG in production — each delivery presented with clear scope, status and evidence.",
      primaryAction: "Explore projects",
      secondaryAction: "Discuss an idea",
      catalogTitle: "Projects",
      catalogHint: "Choose a project or use the Previous and Next buttons.",
      portraitAlt: "Portrait of Guilherme Rocha",
      portraitCaption: "Alfenas, Brazil",
      noscript: "Choose a project:",
    },
    aboutPage: {
      title: "About me — Gui Rocha",
      description: "How Guilherme Rocha takes digital products, local software and creative projects from direction to delivery.",
      eyebrow: "About me",
      heading: "Product direction and technical execution in one process.",
      lead: "Each project begins with the problem, narrows the work to what matters and moves forward in verifiable steps. Concepts, prototypes and products are presented for what they are, with visible limits and current status.",
      primaryAction: "Explore projects",
      secondaryAction: "Open GitHub",
      landscapeAlt: "Guilherme Rocha looking over a canyon and water landscape",
      landscapeKicker: "Map of my work",
      landscapeTitle: "Different scales, the same care for what needs to work.",
      landscapeBody: "ClubAL organizes institutional routines; Maeve builds a world; Checkpoint and NEXUS keep local development oriented; the websites translate each project for its audience.",
      landscapeCaption: "Personal archive · Serra da Canastra",
      catalogKicker: "Explore by context",
      catalogHint: "Hover, use Tab or click to open a category.",
      catalogSingle: "1 project",
      catalogMultiple: "projects",
      catalogs: [
        ["institutional", "Institutional software", ["clubal"]],
        ["games", "Games", ["maeve"]],
        ["websites", "Websites and digital experiences", ["sites"]],
        ["windows", "Windows tools", ["nexus", "codex-checkpoint"]],
        ["resources", "Resources", ["local-first-checklist", "c7-engineering-system"]],
      ],
      methodTitle: "My process",
      method: [
        ["01", "Product", "The problem, audience and decision guide the first product slice."],
        ["02", "Build", "Small steps keep scope, experience and maintenance under control."],
        ["03", "Evidence", "Tests support what can be claimed; anything still evolving remains explicit."],
      ],
    },
    contactPage: {
      title: "Contact — Gui Rocha",
      description: "Contact me directly through business WhatsApp, email or GitHub.",
      eyebrow: "Direct contact",
      heading: "Choose the channel that fits the context.",
      lead: "The conversation comes directly to me, with no form, account or automated queue. Use WhatsApp for a business opening, email for longer context or GitHub to review public work.",
      whatsapp: "Business WhatsApp",
      whatsappDetail: "Send me a message",
      githubDetail: "@gmdr2022",
    },
    privacyPage: {
      title: "Privacy — Gui Rocha",
      description: "Privacy, cookie and local storage policy for Gui Rocha’s portfolio.",
      eyebrow: "Privacy",
      heading: "Minimal collection and local controls.",
      lead: "This portfolio does not use advertising, marketing pixels, user accounts, forms or analytics. Visual preferences stay in your browser.",
      updated: "Last updated: July 26, 2026.",
      indexTitle: "On this page",
      sections: [
        {
          id: "data",
          title: "Data and hosting",
          body: "The code does not create profiles or receive form data. Cloudflare hosts and serves the files and may process technical request metadata under its own policies and operational needs. This portfolio does not add a database or public log access.",
        },
        {
          id: "cookies",
          title: "Cookies and local storage",
          body: "The gui_consent cookie records for up to 180 days whether you chose essential storage only or allowed preferences. Theme and accessibility settings remain in localStorage only with permission; otherwise they last for the session. The portal does not keep its own service worker cache; the current code removes legacy registrations and caches for this domain.",
        },
        {
          id: "external",
          title: "External links",
          body: "WhatsApp, GitHub, email and project websites only receive a navigation when you choose to open the link. From that point, the selected service handles data under its own terms.",
        },
        {
          id: "controls",
          title: "Your controls",
          body: "The Cookies button lets you change your choice. The accessibility button adjusts text size, contrast, motion and font. You can also clear cookies, storage and cache in your browser settings.",
        },
        {
          id: "privacy-contact",
          title: "Contact",
          body: "Questions about this page can be sent to suporte.clubal@gmail.com.",
        },
      ],
    },
    notFoundPage: {
      title: "Page not found — Gui Rocha",
      eyebrow: "Error 404",
      heading: "This address does not exist.",
      lead: "The project catalog is still available. Return to the projects or contact me.",
      primaryAction: "Explore projects",
      secondaryAction: "Contact",
    },
  },
  es: {
    htmlLang: "es",
    ogLocale: "es_ES",
    short: "ES",
    nativeName: "Español",
    home: "/es/",
    routes: {
      about: "/es/sobre/",
      contact: "/es/contacto/",
      privacy: "/es/privacidad/",
      projects: "/es/proyectos/",
      sites: "/es/sitios/",
    },
    common: {
      brandTagline: "Producto · software · creación",
      navLabel: "Navegación principal",
      products: "Proyectos",
      about: "Sobre mí",
      contact: "Contacto",
      talk: "Hablar conmigo",
      theme: "Cambiar tema",
      themeInitial: "Tema: sistema",
      language: "Idioma",
      languageMenu: "Elegir idioma",
      skip: "Ir al contenido",
      footerLabel: "Pie de página",
      privacy: "Privacidad",
      cookies: "Cookies",
      email: "Correo",
      previous: "Anterior",
      next: "Siguiente",
      viewProject: "Ver proyecto",
      backToProjects: "Volver a proyectos",
      nextProject: "Siguiente proyecto",
      galleryPrevious: "Imagen anterior",
      galleryNext: "Siguiente imagen",
      galleryLabel: "Galería del proyecto",
      detailsLabel: "Detalles del proyecto",
      external: "se abre en una pestaña nueva",
      copyright: "Guilherme Rocha.",
    },
    homePage: {
      title: "Gui Rocha — productos digitales, software y sitios",
      description: "Portafolio de Guilherme Rocha: software local-first, herramientas para Windows, sitios publicados y un RPG en producción, con alcance, estado y evidencias claros.",
      eyebrow: "Gui Rocha · producto y creación digital",
      heading: "Productos digitales para organizar operaciones, orientar decisiones y construir experiencias propias.",
      lead: "Software local-first, herramientas para Windows, sitios a medida y un RPG en producción: cada entrega presentada con alcance, estado y evidencias claros.",
      primaryAction: "Explorar proyectos",
      secondaryAction: "Conversar sobre una idea",
      catalogTitle: "Proyectos",
      catalogHint: "Elija un proyecto o use los botones Anterior y Siguiente.",
      portraitAlt: "Retrato de Guilherme Rocha",
      portraitCaption: "Alfenas, Brasil",
      noscript: "Elija un proyecto:",
    },
    aboutPage: {
      title: "Sobre mí — Gui Rocha",
      description: "Cómo Guilherme Rocha lleva productos digitales, software local y proyectos creativos desde la dirección hasta la entrega.",
      eyebrow: "Sobre mí",
      heading: "Dirección de producto y ejecución técnica en un mismo proceso.",
      lead: "Cada proyecto empieza por el problema, reduce el trabajo a lo esencial y avanza en etapas verificables. Conceptos, prototipos y productos se presentan por lo que son, con límites y estado actual visibles.",
      primaryAction: "Explorar proyectos",
      secondaryAction: "Abrir GitHub",
      landscapeAlt: "Guilherme Rocha observando un paisaje de cañones y agua",
      landscapeKicker: "Mapa de mi trabajo",
      landscapeTitle: "Escalas diferentes, el mismo cuidado con lo que debe funcionar.",
      landscapeBody: "ClubAL organiza rutinas institucionales; Maeve construye un mundo; Checkpoint y NEXUS mantienen orientado el desarrollo local; los sitios traducen cada proyecto para su público.",
      landscapeCaption: "Archivo personal · Serra da Canastra",
      catalogKicker: "Explorar por contexto",
      catalogHint: "Pase el cursor, use Tab o haga clic para abrir una categoría.",
      catalogSingle: "1 proyecto",
      catalogMultiple: "proyectos",
      catalogs: [
        ["institutional", "Software institucional", ["clubal"]],
        ["games", "Juegos", ["maeve"]],
        ["websites", "Sitios y experiencias digitales", ["sites"]],
        ["windows", "Herramientas para Windows", ["nexus", "codex-checkpoint"]],
        ["resources", "Recursos", ["local-first-checklist", "c7-engineering-system"]],
      ],
      methodTitle: "Mi proceso",
      method: [
        ["01", "Producto", "Problema, público y decisión orientan el primer recorte del producto."],
        ["02", "Construcción", "Etapas pequeñas mantienen bajo control el alcance, la experiencia y el mantenimiento."],
        ["03", "Evidencia", "Las pruebas sostienen lo que puede afirmarse; lo que aún evoluciona permanece explícito."],
      ],
    },
    contactPage: {
      title: "Contacto — Gui Rocha",
      description: "Hable conmigo directamente por WhatsApp comercial, correo o GitHub.",
      eyebrow: "Contacto directo",
      heading: "Elija el canal más útil para el contexto.",
      lead: "La conversación llega directamente a mí, sin formulario, registro ni cola automática. Use WhatsApp para un inicio comercial, correo para un contexto más amplio o GitHub para conocer el trabajo público.",
      whatsapp: "WhatsApp comercial",
      whatsappDetail: "Enviarme un mensaje",
      githubDetail: "@gmdr2022",
    },
    privacyPage: {
      title: "Privacidad — Gui Rocha",
      description: "Política de privacidad, cookies y almacenamiento local del portafolio de Gui Rocha.",
      eyebrow: "Privacidad",
      heading: "Recopilación mínima y controles locales.",
      lead: "Este portafolio no usa publicidad, píxeles de marketing, cuentas de usuario, formularios ni analítica. Las preferencias visuales permanecen en su navegador.",
      updated: "Última actualización: 26 de julio de 2026.",
      indexTitle: "En esta página",
      sections: [
        {
          id: "datos",
          title: "Datos y hospedaje",
          body: "El código no crea perfiles ni recibe datos por formulario. Cloudflare hospeda y entrega los archivos y puede procesar metadatos técnicos de las solicitudes según sus políticas y necesidades operativas. Este portafolio no añade una base de datos ni acceso público a registros.",
        },
        {
          id: "cookies",
          title: "Cookies y almacenamiento local",
          body: "La cookie gui_consent registra durante hasta 180 días si eligió solo lo esencial o permitió preferencias. El tema y los ajustes de accesibilidad permanecen en localStorage solo con permiso; sin él, duran durante la sesión. El portal no mantiene una caché propia mediante service worker; el código actual elimina registros y cachés heredados de este dominio.",
        },
        {
          id: "externos",
          title: "Enlaces externos",
          body: "WhatsApp, GitHub, correo y los sitios de proyectos solo reciben una navegación cuando usted decide abrir el enlace. A partir de ese momento, el servicio elegido trata los datos según sus propios términos.",
        },
        {
          id: "controles",
          title: "Sus controles",
          body: "El botón Cookies permite cambiar su elección. El botón de accesibilidad ajusta tamaño del texto, contraste, movimiento y fuente. También puede borrar cookies, almacenamiento y caché en el navegador.",
        },
        {
          id: "contacto-privacidad",
          title: "Contacto",
          body: "Las preguntas sobre esta página pueden enviarse a suporte.clubal@gmail.com.",
        },
      ],
    },
    notFoundPage: {
      title: "Página no encontrada — Gui Rocha",
      eyebrow: "Error 404",
      heading: "Esta dirección no existe.",
      lead: "El catálogo de proyectos sigue disponible. Vuelva a los proyectos o hable conmigo.",
      primaryAction: "Explorar proyectos",
      secondaryAction: "Contacto",
    },
  },
};
